language: generic

sudo: required

before_install: 
  openssl aes-256-cbc -K $encrypted_9b522f2f6d89_key -iv $encrypted_9b522f2f6d89_iv -in ci/pgp/key.asc.enc -out ci/pgp/key.asc -d

before_script: ./ci/setup.sh

script: ./ci/run.sh

deploy:
  provider: script
  script: ./ci/deploy.sh
  on:
    branch: master
