apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ripple-auth
  labels:
    app: ripple-auth
    release: {{ .Release.Name }}
spec:
  selector:
    app: ripple-auth
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 3000
