apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ripple-auth
  labels:
    app: ripple-auth
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas.auth }}
  selector:
    matchLabels:
      app: ripple-auth
  template:
    metadata:
      labels:
        app: ripple-auth
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-ripple-auth
          image: {{ .Values.images.auth.image }}:{{ .Values.images.auth.tag }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: key-volume
              readOnly: true
              mountPath: /etc/config
          env:
            - name: PUBLIC_DOMAIN
              value: "{{ .Values.url.protocol }}://{{ .Values.url.baseDomain }}"
            - name: AUTH_DOMAIN
              value: "{{ .Values.url.protocol }}://{{ .Values.url.authSubdomain }}.{{ .Values.url.baseDomain }}"
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: cookieSecret
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: redisPassword
            - name: POSTGRES_HOST
              value: "{{ .Values.databases.auth.host }}"
            - name: POSTGRES_USERNAME
              value: "{{ .Values.databases.auth.user }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: authPostgresqlPassword
            - name: POSTGRES_DATABASE
              value: "{{ .Values.databases.auth.databaseName }}"
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: mailgunApiKey
            - name: MAILGUN_API_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: mailgunApiDomain
            - name: PUBLIC_KEY_LOCATION
              value: "/etc/config/public_key.pem"
            - name: PRIVATE_KEY_LOCATION
              value: "/etc/config/private_key.pem"
            - name: NODE_ENV
              value: "production"
      volumes:
        - name: key-volume
          secret:
            secretName: ripple-rsa-secrets
