apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ripple-core-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ripple-core-api-role
subjects:
  - kind: ServiceAccount
    name: ripple-core-api-serviceaccount
