apiVersion: v1
kind: Secret
metadata:
  name: ripple-rsa-secrets
type: Opaque
data: 
  public_key.pem:
    {{ required "publicKey is required" .Values.publicKey | b64enc }}
  private_key.pem:
    {{ required "privateKey is required" .Values.privateKey | b64enc }}
