apiVersion: v1
kind: Secret
metadata:
  name: ripple-secrets
type: Opaque
data: 
  coreApiPostgresqlPassword: {{ .Values.databases.coreApi.password | b64enc }}
  authPostgresqlPassword: {{ .Values.databases.auth.password | b64enc }}
  redisPassword: {{ .Values.redis.password | b64enc }}
  cookieSecret: {{ .Values.cookieSecret | b64enc }}
  mailgunApiKey: {{ .Values.mailgun.apiKey | b64enc }}
  mailgunApiDomain: {{ .Values.mailgun.apiDomain | b64enc }}
  youtubeApiKey: {{ .Values.youtubeApiKey | b64enc }}
  soundcloudApiKey: {{ .Values.soundcloudApiKey | b64enc }}
