apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ripple-web
  labels:
    app: ripple-web
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      app: ripple-web
  template:
    metadata:
      labels:
        app: ripple-web
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-ripple-web
          image: {{ .Values.images.web.image }}:{{ .Values.images.web.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: RIPPLE_URL
              value: "{{ .Values.url.protocol }}://{{ .Values.url.baseDomain }}"
            - name: CORE_API_URL
              value: "{{ .Values.url.protocol }}://{{ .Values.url.apiSubdomain }}.{{ .Values.url.baseDomain }}"
            - name: AUTH_URL
              value: "{{ .Values.url.protocol }}://{{ .Values.url.authSubdomain }}.{{ .Values.url.baseDomain }}"
            - name: CORE_API_URL_INTERNAL
              value: "http://{{ .Release.Name }}-ripple-core-api:4000"
            - name: AUTH_URL_INTERNAL
              value: "http://{{ .Release.Name }}-ripple-auth:3000"
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: youtubeApiKey
            - name: SOUNDCLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ripple-secrets
                  key: soundcloudApiKey
            - name: OAUTH_CLIENT_NAME
              value: "{{ .Values.oauth2ClientName }}"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
