apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ripple-web
  labels:
    app: ripple-web
    release: {{ .Release.Name }}
spec:
  selector:
    app: ripple-web
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
