apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app: traefik-ingress-controller
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: traefik-ingress-controller
      name: traefik-ingress-controller
  template:
    metadata:
      labels:
        app: traefik-ingress-controller
        name: traefik-ingress-controller
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Release.Name }}-traefik-ingress-controller
          image: traefik:1.7-alpine
          volumeMounts:
            - name: traefik-configmap-volume
              mountPath: /etc/traefik/
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --api
            - --kubernetes
            - --logLevel=INFO
      volumes:
        - name: traefik-configmap-volume
          configMap:
            name: traefik-configmap
