apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: kube-system
data:
  traefik.toml: |
    {{ if eq .Values.url.protocol "https" }}
    defaultEntryPoints = ["http", "https"]
    {{ else }}
    defaultEntryPoints = ["http"]
    {{ end }}
    debug = false
    logLevel = "INFO"

    # Redirect http to https
    {{ if eq .Values.url.protocol "https" }}
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]
        [entryPoints.https.redirect]
          permanent = true
          regex = "^https://www.(.*)"
          replacement = "https://$1"
    {{ else }}
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
    {{ end }}

    [kubernetes]

    [ping]
      entryPoint = "http"
    
    {{ if eq .Values.url.protocol "https" }}
    [acme]
      email = "{{ .Values.acme.email }}"
      storage = "acme.json"
      acmeLogging = true
      onHostRule = true
      entryPoint = "https"
      caServer = "{{ .Values.acme.caServer }}"
      [acme.httpChallenge]
        entryPoint = "http"

      [[acme.domains]]
        main = "{{ .Values.url.baseDomain }}"
        sans = ["www.{{ .Values.url.baseDomain }}", "{{ .Values.url.apiSubdomain}}.{{ .Values.url.baseDomain }}", "{{ .Values.url.authSubdomain }}.{{ .Values.url.baseDomain }}"]
    {{ end }}
