repositories:
  - name: jetstack
  url: https://charts.jetstack.io

releases:
  - name: "traefik"
    namespace: "kube-system"
    chart:  "../charts/traefik"
    values:
      - "../values/ripple.yaml.gotmpl"
      - "../values/traefik.yaml"
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.13.0
