repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com/

releases:
  - name: "traefik"
    namespace: "kube-system"
    chart:  "../charts/traefik"
    values:
      - "../values/ripple.yaml.gotmpl"
      - "../values/traefik.yaml"
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 0.13.0
  - name: cert-manager-cluster-issuer
    namespace: cert-manager
    chart: incubator/raw
    values:
      resources:
        - apiVersion: cert-manager.io/v1alpha2
          kind: ClusterIssuer
          metadata: acme-issuer
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: danielrudn@gmail.com
              privateKeySecretRef:
                name: letsencrypt
              solvers:
                - selector: {}
                  http01:
                    ingress: {}
              
